gcrk/seir41-homework

Lionel-James Pengilley/week_01/week_01

6-7
no
no
Did I miss anything?
20-30 minutes

Added a text file to see if the changes would appear

---

Aron Weston/week_1/day_2/calculator/calc.js
Aron Weston/week_1/day_2/calculator/calculator.html
Aron Weston/week_1/day_2/strings/strings.html
Aron Weston/week_1/day_2/strings/strings.js

**_If you had no problems you can just leave it empty_**
Not that much, I didn't get on to the last one for Section 2 but I'll get on to it after class. If you want me to not use arrow functions, I will. It's just a habit now. 
**> How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible**
5/10. 
**> Was there anything that you struggled with?**
Section 2 - messing around with substrings and slice. Not sure if its kosher to use slice on strings outside of arrays. I could probably also use more detailed methods to have fewer lines.
N/A
Is there a simpler way to go about Section 2 questions. I feel like I'm writing too much code to get …

#1: W1_D3: Calculator & Strings

---

Jye Harry/1-week/tuesday/calculator/index.html
Jye Harry/1-week/tuesday/calculator/js/exercises.js
Jye Harry/1-week/tuesday/strings/index.html
Jye Harry/1-week/tuesday/strings/js/exercises.js

3/10
The fixStart function in the strings exercice took me the longest to do.
3 hours

tuesday homework. calculator and strings.

---

Scott Causby/week01/tuesday8th.html
Scott Causby/week01/tuesday8th.js
Scott Causby/week01/wednesday9th.html
Scott Causby/week01/wednesday9th.js

9
writing code from scratch is very hard for me. If code is already written it is very easy for me to read and edit things.
check that drEvil is correct please
no
5-6 hours

Tuesdays homework

---

Natalie Pauchard/week01/calculator/index.html
Natalie Pauchard/week01/calculator/js/exercises.js

Part 1: 6.5/10 - once I got the first one working, the rest completed fairly quickly and everything worked in the console without much back and forth which was surprising given how many errors I was getting while doing all the exercises previously.
Part 2: 10/10 - wasn't sure what exactly the instructions were asking me to do.
Part 1 - unsure what the best way was to write the code, had to Google a few minor things like fixed decimal places
Part 2 - unsure what I had to do
Realised this morning there are probably better ways to write the code …

Calculator_Part1

---

Lionel-James Pengilley/week_01/day3/index.html
Lionel-James Pengilley/week_01/day3/js/exercises.js

homework day 3

---

Trent Thompson/week1/day 3/index.html
Trent Thompson/week1/day 3/js/homwork.js

> How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible - 8 - this takes me a very long time to come up with code
> Was there anything that you struggled with? 
I kept creating arguments, which i thought we could pass anythung into but it kept saying error undefined to what ever work i was passing in.  
I got it to work with the number add and multipy....but not entirely sure if its good code
all of it please
I guess just the correct answers so i can look them through
too long. 2 hrs maybe and a bit of mucking about with github and iTerm and …

array_and_functions

---

Aron Weston/week_1/day_3/array/array.html
Aron Weston/week_1/day_3/array/array.js
Aron Weston/week_1/day_3/word_guesser/word.html
Aron Weston/week_1/day_3/word_guesser/word.js

These were a bit tricky, (7/10). I'll finish up the word guesser on the weekend and see if I can do it in a different way. 
The word guesser. 

Week 1 - Day 3

---

Natalie Pauchard/week01/array and functions/index.html
Natalie Pauchard/week01/array and functions/js/exercises.js
Natalie Pauchard/week01/objects/index.html
Natalie Pauchard/week01/objects/js/exercises.js
Natalie Pauchard/week01/strings/index.html
Natalie Pauchard/week01/strings/js/exercises.js

7
Was not sure whether I had to make equilateral and isosceles triangles different - after a lot of deliberating I left them to log as the same cause they are  
If there is any thing I could have done differently or more efficiently
I didn't get to the next two exercises 👍 
Hard to tell finished just after 8pm I think but that was with a lot of back and forth with other students

Thurs_HW_rectangle_triangle

---

Lionel-James Pengilley/week_01/day4/index.html
Lionel-James Pengilley/week_01/day4/js/exercises.js

10
- The isIsosceles function
- The cashRegister function
- The validateCreditCard function
- line 199
- see comment in line 199
4 hours

day 4 homework

---

Aron Weston/week_1/day_4/TODO.md
Aron Weston/week_1/day_4/cash_register/cash.html
Aron Weston/week_1/day_4/cash_register/cash.js
Aron Weston/week_1/day_4/credit_card/credit.html
Aron Weston/week_1/day_4/credit_card/credit.js
Aron Weston/week_1/day_4/geo/geometry.html
Aron Weston/week_1/day_4/geo/geometry.js
Aron Weston/week_1/day_4/missed_exercises/objects.js

**> How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible**
6/10 - I didn't really finish the first or last question so hard to tell. In terms of saving the response to the object as per today's topic, that wasn't too tricky. 
I think its mostly just finding time for the quantity but that will come with time. 
**> Was there anything that you struggled with?**
I'm pretty sure I could have done the credit card checker into separate functions and have them return their values to each other. I've added that to this week's todos. 
**> Is there any particular code you want me to look into?**
I struggle with some of the maths stuff tbh. My brain shuts off and goes to the fun logic-based stuff and …

W1_D4: Geometry, Credit Check & Cash Machine. Check TODO.md for details

---

Danielle Steele/week1/day3/homework.js
Danielle Steele/week1/day4objectsArrays/homework.js
Danielle Steele/week1/day4objectsArrays/index.html
Danielle Steele/week1/weekend/index.html
Danielle Steele/week1/weekend/weekend.js

7, however I had support from my friend, without him I am unsure I would have got this finished. 
1. I am still struggling with the foundations of functions, I find them confusing and am yet to understand the pattern properly. 
1a. I am also struggling to understand how the values get passed around and how that works. 
2. I am getting mixed up between arrays and objects in arrays. / Arrays and Objects. 
3. Is an If Statement a function? They seem to work in a very similar way. 
----
Not at this stage, but some feedback and discussion on above points would be appreciated 
> Is there anything …

Dani Steele: Weekend1 Subway

---

Jye Harry/1-week/mta/index.html
Jye Harry/1-week/mta/js/exercises.js
Jye Harry/1-week/thursday/credit-card-validation/js/exercises.js

8
not really, just had to work my through it.
around 10 hours

finished the mta lab

---

Amish Adhikari/week1/Week-1-Weekendhomework/homework1.js
Amish Adhikari/week1/Week-1-Weekendhomework/index.html

Can you please scan my code and advise if the codes has been duplicated.
The whole code. Thanks
8 hours

Week-1-Weekend-homework

---

Aron Weston/week_1/day_4/credit_card/creditFunc.js
Aron Weston/week_1/day_5/mta.html
Aron Weston/week_1/day_5/mta.js
Aron Weston/week_1/day_5/notes.md

**Updated** I got some text out in the DOM. Pretty nifty.
7/10. This was a tonne of fun. Loved it. I started out with using `.splice()` and got a working prototype but was having trouble flipping the array. Ended up refactoring by using a filter through a `for` loop, then just used the `.filter` method. 
I messed around with some simple validation and using `.prompt()` to get the inputs from the front end. 
Getting the regex right was tricky. `.splice()` is also a confusing method and it can turn into a maths formula really quickly. Definitely liked looking into higher-order array methods. Was …

MTA Lab #2

---

Aron Weston/week_2/day_1/html-labs/brooklyn/index.html
Aron Weston/week_2/day_1/html-labs/busyhands/index.html
Aron Weston/week_2/day_1/html-labs/ecardly/index.html

9/10. I find CSS quite finicky and it's not my favourite language. The issue I have mostly is just lining things up and getting it to work the way that I want it to. This exercise was probably the most difficult as I've only ever copied my own designs. Good challenge though, hopefully, I can get back to them in the break. 
Removing the floats and getting the good hands and the logos to the right to play nicely. I would usually just give up and use flexbox but I was trying to do it the inline-block way and it was very defeating. 
> Is there …

File changes

---

Amish Adhikari/week2/thurshomework/Cat Walk.htm
Amish Adhikari/week2/thurshomework/js/catwalk.js
Amish Adhikari/week2/thurshomework/style/catwalk.css

How do I play music without the bar on top.
7
To get rid of the music bar and get the music going as soon as the page loads
Hey!! thanks for yesterday's comment. Yay!!! finally I can play the music on the browser. 
Happy FriYaay!!! All
4hrs

Catwalk with JQuery

---

Natalie Pauchard/WED_Cat_HW/cat/js/exercises.js

Depends on when I attempted - first attempt was a disaster, second attempt felt 'too easy' ha so I'll give it an average of the two - 7
I kept getting an error about style property being undefined - later found out it was cause I had jQuery script in the wrong place. But after that it was fine (2nd attempt).
If I have any unnecessary code or need to add anything - seems quite short. But I didn't do the Bonus' (want to focus on finishing the ATM HW)
see above
> Roughly how long …

Cat_Walk_HW_wk2

---

Natalie Pauchard/Week04/calculator.rb

Pretty easy once I fixed initial bug 1/10
Just trying to figure out initially why it wasn't working
If there's a better way to write the code - felt like a lot of repetition 
> Is there anything that you'd like some further information on? see above ^^

Ruby_Calculator_Wk4

---

Aron Weston/week_3/calc.rb

I tried to just get this one done, I'll get back to the bonus stuff later.

W3_MON: ruby calculator

---

Natalie Pauchard/Week04/Books/main.rb
Natalie Pauchard/Week04/Books/public/css/book.css
Natalie Pauchard/Week04/Books/views/home.erb
Natalie Pauchard/Week04/Books/views/layout.erb
Natalie Pauchard/Week04/Books/views/result.erb

Depends on which part - first part was fine had a placeholder image that showed up - but then trying to add all the code in main.rb causes lots of errors 8/10
I got the files talking to each other fine, could see it all displayed and  @title = params[:title] worked for the text  - just ended up getting errors with the other lines of code, can't get it pulling from the title from the google book
Will try again tomorrow / weekend to get it working. Thought I'd submit even though it doesn't work just for feedback / guidance
> Is there anything …

Books_Attempt_wk4

---

Yang Wu/week4/Tuesday/MTA.rb
Yang Wu/week4/Wednesday/main.rb
Yang Wu/week4/Wednesday/public/css/book.css
Yang Wu/week4/Wednesday/views/home.erb
Yang Wu/week4/Wednesday/views/layout.erb
Yang Wu/week4/Wednesday/views/result.erb

> Was there anything that you struggled with? 
layout problem: can hardly align the text part with the input part in label.
Some more explanation & exercises about how to find specific data within a large object (like what Joel did yesterday, find the link of the cover picture in that massive object)

Wednesday Homework

---

Jim Carlton/04-week/03-day/ruby-books-1/main.rb
Jim Carlton/04-week/03-day/ruby-books-1/public/css/style.css
Jim Carlton/04-week/03-day/ruby-books-1/views/home.erb
Jim Carlton/04-week/03-day/ruby-books-1/views/layout.erb
Jim Carlton/04-week/03-day/ruby-books-1/views/result.erb

7 - I think this exercise wasn't too difficult - though that's I think because we got the API reference method - drilling down the output from Google wasn't too bad. Though I went down a rabbit hole on Array Methods and kind of got a touch confused - especially with your exercise this morning Stacey - for some reason I didn't have ANY clue on it 🤨 - most other exercises I had _some_ way to get _something_ something out - maybe just a steep learning curve at this point with Ruby. …

W4 D3 - Books 1 Exercise

---

Jim Carlton/07-week/ajax-api-hub/css/style.css
Jim Carlton/07-week/ajax-api-hub/index.html
Jim Carlton/07-week/ajax-api-hub/js/jquery.js
Jim Carlton/07-week/ajax-api-hub/js/main.js
Jim Carlton/07-week/google-books-search/index.html
Jim Carlton/07-week/google-books-search/js/main.js

5
I was a bit rusty on my JS - good exercise to get back into it for the React week ahead. Also I didn't elaborate on the exercise due to a personal issue that came up between classes - aiming to push the homework in the coming days however :)

W7 D1 - Asynchronous Book Search

---

Mai (Chi) Nguyen/week-07/day-01-google-book-ajax/index.html
Mai (Chi) Nguyen/week-07/day-01-google-book-ajax/js/google-book.js
Mai (Chi) Nguyen/week-07/day-02-api-web-app/index-hero.html
Mai (Chi) Nguyen/week-07/day-02-api-web-app/index-joke.html
Mai (Chi) Nguyen/week-07/day-02-api-web-app/js/hero.js
Mai (Chi) Nguyen/week-07/day-02-api-web-app/js/joke.js
Mai (Chi) Nguyen/week-07/day-02-api-web-app/js/jquery.js

HW day02: API-joke-and-hero without css

---

Natalie Pauchard/week05/google-books-ajax copy/css/books.css
Natalie Pauchard/week05/google-books-ajax copy/index.html
Natalie Pauchard/week05/google-books-ajax copy/js/books-ajax.js
Natalie Pauchard/wk7-Tues-HW-space/css/style.css
Natalie Pauchard/wk7-Tues-HW-space/index.html
Natalie Pauchard/wk7-Tues-HW-space/js/jquery.js
Natalie Pauchard/wk7-Tues-HW-space/js/main.js

6 - some parts were easier than others. Not too bad in comparison with other HW
remembering JS :(
CSS - I couldn't center the h1 for ages! Then just created its own ID and it worked
Why I had to use ids to make some of the CSS work - the H1 isn't pulling from anywhere but the html 
Why
Why I had to use ids to make some of the CSS work - the H1 isn't pulling from anywhere but the html 
a few hours

google-books-ajax

---

Danielle Steele/week7/dogAPI/js/index.js
Danielle Steele/week7/dogAPI/js/jquery.js
Danielle Steele/week7/googleSearch/index.html
Danielle Steele/week7/googleSearch/js/index.js

9
I am struggling to untangle DOM, JS, JQuery, and how it all relates to what I am writing. 
I did not get as far as the thumbnails for images. 
xhr and xmlhttp and httparty stuff, please 
Approximately three hours

W7D1: Book-search API HW 

---

Mai (Chi) Nguyen/week-07/day-03-image-search/js/search.js
Mai (Chi) Nguyen/week-07/day-04/recursion-exercises/.gitignore
Mai (Chi) Nguyen/week-07/day-04/recursion-exercises/floodIt-challenge/README.md
Mai (Chi) Nguyen/week-07/day-04/recursion-exercises/floodIt-challenge/app.js
Mai (Chi) Nguyen/week-07/day-04/recursion-exercises/floodIt-challenge/index.html
Mai (Chi) Nguyen/week-07/day-04/recursion-exercises/floodIt-challenge/style.css
Mai (Chi) Nguyen/week-07/day-04/recursion-exercises/package-lock.json
Mai (Chi) Nguyen/week-07/day-04/recursion-exercises/package.json
Mai (Chi) Nguyen/week-07/day-04/recursion-exercises/readme.md
Mai (Chi) Nguyen/week-07/day-04/recursion-exercises/recursion.html
Mai (Chi) Nguyen/week-07/day-04/recursion-exercises/recursion.js
Mai (Chi) Nguyen/week-07/day-04/recursion-exercises/test/index.js
Mai (Chi) Nguyen/week-07/recursion-exercises

HW day 4 - Recursive functions finished -aaaaaaaaaa i need a new brain

---

Andre Anggono/week_07/day_04/recursion-exercises/.gitignore
Andre Anggono/week_07/day_04/recursion-exercises/floodIt-challenge/README.md
Andre Anggono/week_07/day_04/recursion-exercises/floodIt-challenge/app.js
Andre Anggono/week_07/day_04/recursion-exercises/floodIt-challenge/index.html
Andre Anggono/week_07/day_04/recursion-exercises/floodIt-challenge/style.css
Andre Anggono/week_07/day_04/recursion-exercises/package-lock.json
Andre Anggono/week_07/day_04/recursion-exercises/package.json
Andre Anggono/week_07/day_04/recursion-exercises/readme.md
Andre Anggono/week_07/day_04/recursion-exercises/recursion.js
Andre Anggono/week_07/day_04/recursion-exercises/test/index.js

8
Sticking to nested recursion in the letters combinations function
Coin flips and Letters Combinations > Was it done as intended? 
7 hours

W7.D4 - Recursion Exercises

---

Natalie Pauchard/week7/Thurs/recursion-exercises/recursion.js

8
findMax and coin flip - made sense once Joel went through it - couldn't get the last one
no
no
Hours

wk7-thurs-hw-recurssion

---

Natalie Pauchard/week10/stocks-node/index.js
Natalie Pauchard/week10/stocks-node/package-lock.json
Natalie Pauchard/week10/stocks-node/package.json
Natalie Pauchard/week10/stocks-node/views/home.ejs
Natalie Pauchard/week10/stocks-node/views/info.ejs
Natalie Pauchard/week10/stocks-node/views/partials/head.ejs
Natalie Pauchard/week10/stocks-node/views/partials/nav.ejs

wk10-mon-hw-stocks
